### ISSUE TITLE
Android builds not working (multiple issues)

### ISSUE THREAD

**Issue by Discordia** [google/ion#10]
Fails to build for android on Linux Mint 17.3 by doing build:
1. cd ion/
2. edit dev/android_common.gypi to have the corrects paths to my created standalone ndk toolchain
3. ./build.sh -o android-arm

Issues that I have found:
- Fails because the folder android/ and the expected files jniutil.h, jniutil.cc and trace.cc does not exist under port/. (Can get further by editing port/port.gyp to remove the reference to the three files).
- Fails because of a hardocded url to the ndk in ion/external/external.gyp. It's the paths to cpu-features.h and cpu-features.cc.
- Fails when about to create the apk because it expects to find a template AndroidManifest.xml.in in ion/dev/.

**Comment by oon3m0oo** [comment]
Should be working with the latest push.  Please reopen if that's not the case.
