### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [google/ion#11]
Would you like to [replace any double quotes](https://github.com/google/ion/blob/9e659416fb04bb3d3a67df1e018d7c2ccab9d468/ion/base/datacontainer.h#L28) by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename)?

**Comment by oon3m0oo** [comment]
Our internal standard is to use angle brackets only for system includes.  So thanks for the offer, but it's fine as is.  See also:
https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html) from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf) in the standard specification for the programming language "C++".

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid "a duplicated file search" here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html) for header files of your software?
