### ISSUE TITLE
iOS build is failing

### ISSUE THREAD

**Issue by SebastianKeller** [google/ion#15]
Currently, the iOS build is not successful.

I'm running this command:
`python build.py -o ios -c Release`

using the compiler provided by Xcode (Version 7.2)

```
clang++ -v
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```

and getting the following error message:

```
** BUILD FAILED **


The following build commands failed:
    CompileC ion/gyp-out/ios/Release/obj/external_ios.build/Release-iphoneos/ionzlib.build/Objects-normal/armv7/zip.o ion/third_party/zlib/src/contrib/minizip/zip.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
ERROR: Build failed.
```

Cheers

**Comment by SebastianKeller** [comment]
I've found some hints on HN:
https://news.ycombinator.com/item?id=11069570

> > kengonakajima 15 days ago
> > 
> > ## Build fails in Yosemite inside zlib. I forked it and trying to fix it.. Anyone did?
> 
> joeld42 13 days ago
> 
> I don't really understand their build system so not sure how to fix this cleanly but I added:
> `#define NOCRYPT (1) #define NOUNCRYPT (1)` at the top of `./third_party/zlib/src/contrib/minizip/zip.c` and `unzip.c`
> And that got past the zlib errors on yosemite and built some of the demos (I will post some screenshots on twitter @joeld42, but it's just boxes and stuff). [...]

**Comment by SebastianKeller** [comment]
Please see PR: https://github.com/google/ion/pull/16

**Comment by oon3m0oo** [comment]
This is done in the latest push.
