### ISSUE TITLE
ANDROID Build fails on ubuntu 16.10 (x64)

### ISSUE THREAD

**Issue by malcalde** [google/ion#20]
Hi all.

Output of ./build.sh --os android show a lot dependencies issues. How can I fixed them?.

FAILED: if [ ! -e gen/libgearsdemo.so -o ! -e gen/libgearsdemo.so.TOC ]; then /opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -shared -Wl,--fix-cortex-a8 -march=armv7-a -mthumb --sysroot=/opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9 -B /opt/android/ndk/platforms/android-21/arch-arm/usr/lib -Wl,-L/opt/android/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -Wl,--gc-sections -Wl,--no-undefined,-z,nocopyreloc -Wl,-dynamic-linker,/system/bin/linker -lc -lm -ldl -llog -lstdc++ -lgcc -g -o gen/libgearsdemo.so -Wl,-soname=libgearsdemo.so @gen/libgearsdemo.so.rsp && { /opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-readelf -d gen/libgearsdemo.so | grep SONAME ; /opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm -gD -f p gen/libgearsdemo.so | cut -f1-2 -d' '; } > gen/libgearsdemo.so.TOC; else /opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ -shared -Wl,--fix-cortex-a8 -march=armv7-a -mthumb --sysroot=/opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9 -B /opt/android/ndk/platforms/android-21/arch-arm/usr/lib -Wl,-L/opt/android/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a -Wl,--gc-sections -Wl,--no-undefined,-z,nocopyreloc -Wl,-dynamic-linker,/system/bin/linker -lc -lm -ldl -llog -lstdc++ -lgcc -g -o gen/libgearsdemo.so -Wl,-soname=libgearsdemo.so @gen/libgearsdemo.so.rsp && { /opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-readelf -d gen/libgearsdemo.so | grep SONAME ; /opt/android/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm -gD -f p gen/libgearsdemo.so | cut -f1-2 -d' '; } > gen/libgearsdemo.so.tmp && if ! cmp -s gen/libgearsdemo.so.tmp gen/libgearsdemo.so.TOC; then mv gen/libgearsdemo.so.tmp gen/libgearsdemo.so.TOC ; fi; fi
../../../ion/base/shareable.h:41: error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../../ion/base/shareable.h:41: error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::operator<< std::char_traits<char >(std::basic_ostream<char, std::char_traits<char> >&, char const_)'
../../../ion/base/shareable.h:41: error: undefined reference to 'std::ostream::operator<<(int)'
../../../ion/base/shareable.h:41: error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::operator<< std::char_traits<char >(std::basic_ostream<char, std::char_traits<char> >&, char const_)'
../../../ion/base/shareable.h:41: error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::operator<< std::char_traits<char >(std::basic_ostream<char, std::char_traits<char> >&, char const_)'
../../../ion/base/shareable.h:41: error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& std::operator<< std::char_traits<char >(std::basic_ostream<char, std::char_traits<char> >&, char const_)'
../../../ion/base/shareable.h:41: error: undefined reference to 'std::ostream::operator<<(int)'

and so hundred line more.

Thanks in advanced.

Best regards

**Comment by duyu** [comment]
Hey there, did you get it fixed? I saw the same issue now, could you help me out? thx.
