### ISSUE TITLE
Fails to build with clang-3.4

### ISSUE THREAD

**Issue by Discordia** [google/ion#9]
Building on Linux Mint 17.3 (Rosa) with the default version of clang from the package manager: 3.4 fail. It fails because the warning no-unused-local-typedefs is not supported on clang-3.4. By removing the -Wno-unused-local-typedefs from two places in ion/gfx/gfx.gyp it builds successfully.

**Comment by oon3m0oo** [comment]
I think the issue was that -Wno-unused-local-typedef is not supported, but -Wno-unused-local-typedefs is.  The latest push uses the latter (this was also broken on Android builds).
